#spring.security.user.name=test
#spring.security.user.password=test123

spring:
#  security:
#    user:
#      name: test
#      password: test123
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_demo
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

